/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.imjustcoding.ContactBook;

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author User
 */
public class ContactBookForm extends javax.swing.JFrame {

    /**
     * Creates new form ContactBookForm
     */
    String imagePth=null;
    public static int currentUserId;
    public ContactBookForm() {
        initComponents();
        populateJTable();
        setTableProperties();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_UserPic = new javax.swing.JLabel();
        jLabel_Username = new javax.swing.JLabel();
        jButton_DeleteContact1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField_Id = new javax.swing.JTextField();
        jTextField_FName = new javax.swing.JTextField();
        jTextField_LName = new javax.swing.JTextField();
        jTextField_Phone = new javax.swing.JTextField();
        jTextField_Email = new javax.swing.JTextField();
        jComboBox_Group = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel_Pic = new javax.swing.JLabel();
        jButton_Browse = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_Address = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton_First = new javax.swing.JButton();
        jButton_Next = new javax.swing.JButton();
        jButton_Previous = new javax.swing.JButton();
        jButton_Last = new javax.swing.JButton();
        jButton_DeleteContact = new javax.swing.JButton();
        jButton_EditContact = new javax.swing.JButton();
        jButton_AddContact = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(27, 163, 156));

        jPanel2.setBackground(new java.awt.Color(25, 181, 254));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel1.setText("My Contacts");

        jLabel_UserPic.setBackground(new java.awt.Color(51, 255, 51));
        jLabel_UserPic.setForeground(new java.awt.Color(255, 0, 255));
        jLabel_UserPic.setText("jLabel2");
        jLabel_UserPic.setOpaque(true);

        jLabel_Username.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel_Username.setForeground(new java.awt.Color(204, 255, 255));
        jLabel_Username.setText("#####");

        jButton_DeleteContact1.setBackground(new java.awt.Color(255, 102, 102));
        jButton_DeleteContact1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_DeleteContact1.setForeground(new java.awt.Color(255, 255, 255));
        jButton_DeleteContact1.setText("LogOut");
        jButton_DeleteContact1.setBorderPainted(false);
        jButton_DeleteContact1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DeleteContact1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel_UserPic, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jLabel_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(217, 217, 217)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_DeleteContact1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_UserPic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButton_DeleteContact1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel_Username))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 255));
        jLabel4.setText("ID:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 255));
        jLabel5.setText("First Name:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 255, 255));
        jLabel6.setText("Last Name:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 255, 255));
        jLabel7.setText("Phone:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 255, 255));
        jLabel8.setText("Email:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 255, 255));
        jLabel9.setText("Group:");

        jTextField_Id.setBackground(new java.awt.Color(101, 198, 187));
        jTextField_Id.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_Id.setForeground(new java.awt.Color(31, 58, 147));

        jTextField_FName.setBackground(new java.awt.Color(101, 198, 187));
        jTextField_FName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_FName.setForeground(new java.awt.Color(31, 58, 147));

        jTextField_LName.setBackground(new java.awt.Color(101, 198, 187));
        jTextField_LName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_LName.setForeground(new java.awt.Color(31, 58, 147));

        jTextField_Phone.setBackground(new java.awt.Color(101, 198, 187));
        jTextField_Phone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_Phone.setForeground(new java.awt.Color(31, 58, 147));

        jTextField_Email.setBackground(new java.awt.Color(101, 198, 187));
        jTextField_Email.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_Email.setForeground(new java.awt.Color(31, 58, 147));

        jComboBox_Group.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox_Group.setForeground(new java.awt.Color(31, 58, 147));
        jComboBox_Group.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Family", "Friends", "Work" }));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 255, 255));
        jLabel10.setText("Address:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 255, 255));
        jLabel11.setText("Profile Picture:");

        jLabel_Pic.setBackground(new java.awt.Color(51, 110, 123));
        jLabel_Pic.setOpaque(true);

        jButton_Browse.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Browse.setText("Browse");
        jButton_Browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BrowseActionPerformed(evt);
            }
        });

        jTextArea_Address.setBackground(new java.awt.Color(101, 198, 187));
        jTextArea_Address.setColumns(20);
        jTextArea_Address.setRows(5);
        jScrollPane1.setViewportView(jTextArea_Address);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "First Name", "Last Name", "Group", "Phone", "Email", "Address", "Image"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jButton_First.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_First.setText("<<");
        jButton_First.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_FirstActionPerformed(evt);
            }
        });

        jButton_Next.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_Next.setText("<");
        jButton_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_NextActionPerformed(evt);
            }
        });

        jButton_Previous.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_Previous.setText(">");
        jButton_Previous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_PreviousActionPerformed(evt);
            }
        });

        jButton_Last.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_Last.setText(">>");
        jButton_Last.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LastActionPerformed(evt);
            }
        });

        jButton_DeleteContact.setBackground(new java.awt.Color(255, 51, 51));
        jButton_DeleteContact.setForeground(new java.awt.Color(255, 255, 255));
        jButton_DeleteContact.setText("Delete");
        jButton_DeleteContact.setBorderPainted(false);
        jButton_DeleteContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DeleteContactActionPerformed(evt);
            }
        });

        jButton_EditContact.setBackground(new java.awt.Color(51, 153, 255));
        jButton_EditContact.setForeground(new java.awt.Color(255, 255, 255));
        jButton_EditContact.setText("Edit");
        jButton_EditContact.setBorderPainted(false);
        jButton_EditContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EditContactActionPerformed(evt);
            }
        });

        jButton_AddContact.setBackground(new java.awt.Color(0, 204, 102));
        jButton_AddContact.setForeground(new java.awt.Color(255, 255, 255));
        jButton_AddContact.setText("Add");
        jButton_AddContact.setBorderPainted(false);
        jButton_AddContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddContactActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(101, 198, 187));
        jSeparator1.setForeground(new java.awt.Color(101, 198, 187));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_Id)
                            .addComponent(jTextField_Email, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                            .addComponent(jTextField_Phone, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                            .addComponent(jTextField_LName, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                            .addComponent(jTextField_FName, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                            .addComponent(jComboBox_Group, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(214, 214, 214)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jButton_First)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_Next)
                        .addGap(59, 59, 59)
                        .addComponent(jButton_Previous)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_Last)))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_Pic, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Browse))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jButton_DeleteContact)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_EditContact, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(46, 46, 46)
                            .addComponent(jButton_AddContact, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(157, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jTextField_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addGap(65, 65, 65)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jTextField_FName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jTextField_LName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel_Pic, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Browse))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(jTextField_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(jTextField_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(jComboBox_Group, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1)))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_First)
                    .addComponent(jButton_Next)
                    .addComponent(jButton_Previous)
                    .addComponent(jButton_Last)
                    .addComponent(jButton_DeleteContact)
                    .addComponent(jButton_EditContact)
                    .addComponent(jButton_AddContact))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setTableProperties(){
        jTable1.setShowGrid(true);
        jTable1.setGridColor(Color.BLUE);
        jTable1.setSelectionBackground(Color.cyan);
        jTable1.setSelectionForeground(Color.DARK_GRAY);
        JTableHeader th= jTable1.getTableHeader();
        
        th.setForeground(Color.BLUE);
        th.setFont(new Font("Tahoma", Font.PLAIN, 14));
    }
    
    public void populateJTable(){
        ContactQuery cq=new ContactQuery();
        ArrayList<Contact> ctList=cq.contactList(currentUserId);
        
        String[] colNames={"Id","First Name","Last Name","Group","Phone","Email","Address","Image"};
        Object[][] rows=new Object[ctList.size()][8];
        
        for (int i = 0; i < ctList.size(); i++) {
            rows[i][0]=ctList.get(i).getCid();
            rows[i][1]=ctList.get(i).getfName();
            rows[i][2]=ctList.get(i).getlName();
            rows[i][3]=ctList.get(i).getGroupc();
            rows[i][4]=ctList.get(i).getPhone();
            rows[i][5]=ctList.get(i).getEmail();
            rows[i][6]=ctList.get(i).getAddress();
            
            ImageIcon pic=new ImageIcon(new ImageIcon(ctList.get(i).getPic())
                                                        .getImage()
                                                        .getScaledInstance(120, 80, Image.SCALE_SMOOTH));
            
            rows[i][7]=pic;
            
        }
        
        MyModel mm=new MyModel(rows, colNames);
        jTable1.setModel(mm);
        jTable1.setRowHeight(80);
        jTable1.getColumnModel().getColumn(7).setPreferredWidth(120);
    }
    
    public void clearFields(){
        jTextField_Id.setText("");
        jTextField_FName.setText("");
        jTextField_LName.setText("");
        jTextField_Phone.setText("");
        jTextField_Email.setText("");
        jTextArea_Address.setText("");
        jComboBox_Group.setSelectedIndex(0);
        jLabel_Pic.setIcon(null);
        imagePth=null;
    }
    
    public boolean verifData(){
        if(jTextField_FName.getText().equals("")&&jTextField_LName.getText().equals("")||jTextField_Phone.getText().equals("")||jTextField_Email.getText().equals("")||jTextArea_Address.getText().equals("")){
            JOptionPane.showMessageDialog(null,"One or more fields are empty!");
            return false;
        }else{
            return true;
        }
            
    }
    
    
    private void jButton_BrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BrowseActionPerformed
        MyFunction mf=new MyFunction();
        imagePth = mf.browseImage(jLabel_Pic);
    }//GEN-LAST:event_jButton_BrowseActionPerformed

    private void showData(int rowIndex){
        jTextField_Id.setText(jTable1.getValueAt(rowIndex, 0).toString());
        jTextField_FName.setText(jTable1.getValueAt(rowIndex, 1).toString());
        jTextField_LName.setText(jTable1.getValueAt(rowIndex, 2).toString());
        jComboBox_Group.setSelectedItem(jTable1.getValueAt(rowIndex,3).toString());
        jTextField_Phone.setText(jTable1.getValueAt(rowIndex, 4).toString());
        jTextField_Email.setText(jTable1.getValueAt(rowIndex, 5).toString());
        jTextArea_Address.setText(jTable1.getValueAt(rowIndex, 6).toString());
        
        Image pic=((ImageIcon)jTable1.getValueAt(rowIndex, 7)).getImage().getScaledInstance(jLabel_Pic.getWidth(), jLabel_Pic.getWidth(), Image.SCALE_SMOOTH);
        ImageIcon img = new ImageIcon(pic);
        
        jLabel_Pic.setIcon(img);
    }
    
    private void jButton_AddContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddContactActionPerformed
        
        if(verifData()){
            String fName=jTextField_FName.getText();
            String lName=jTextField_LName.getText();
            String phone=jTextField_Phone.getText();
            String email=jTextField_Email.getText();
            String address=jTextArea_Address.getText();
            String group=jComboBox_Group.getSelectedItem().toString();
            
            if(imagePth!=null){
                byte[] img=null;
                try {
                    Path pth=Paths.get(imagePth);
                    img = Files.readAllBytes(pth);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(ContactBookForm.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(ContactBookForm.class.getName()).log(Level.SEVERE, null, ex);
                }

                Contact c=new Contact(null, fName, lName, group, phone, email, address, img, currentUserId);
                ContactQuery cq=new ContactQuery();
                cq.insertContact(c);

                jTable1.setModel(new DefaultTableModel());
                populateJTable();
                setTableProperties();
                clearFields();
            }else{
                JOptionPane.showMessageDialog(null, "Choose a picture, please!");
            }
            
            
        }
    }//GEN-LAST:event_jButton_AddContactActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // display selected JTable row data
        
        // get selected row index
        int rowIndex = jTable1.getSelectedRow();
        showData(rowIndex);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton_EditContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EditContactActionPerformed

        if(verifData()){
            int id=Integer.valueOf(jTextField_Id.getText());
            String fName=jTextField_FName.getText();
            String lName=jTextField_LName.getText();
            String phone=jTextField_Phone.getText();
            String email=jTextField_Email.getText();
            String address=jTextArea_Address.getText();
            String group=jComboBox_Group.getSelectedItem().toString();

            if(imagePth!=null){
                byte[] img=null;
                try {
                    Path pth=Paths.get(imagePth);
                    img = Files.readAllBytes(pth);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(ContactBookForm.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(ContactBookForm.class.getName()).log(Level.SEVERE, null, ex);
                }

                Contact c=new Contact(id, fName, lName, group, phone, email, address, img, currentUserId);
                ContactQuery cq=new ContactQuery();
                cq.updateContact(c, true);

                jTable1.setModel(new DefaultTableModel());
                populateJTable();
                setTableProperties();
                clearFields();
            }else{
                Contact c=new Contact(id, fName, lName, group, phone, email, address, null, currentUserId);
                ContactQuery cq=new ContactQuery();
                cq.updateContact(c, false);

                jTable1.setModel(new DefaultTableModel());
                populateJTable();
                setTableProperties();
                clearFields();
            }
        }   
    }//GEN-LAST:event_jButton_EditContactActionPerformed

    private void jButton_DeleteContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DeleteContactActionPerformed
       
        
        if(!jTextField_Id.getText().equals("")){
            Integer id=Integer.valueOf(jTextField_Id.getText());
            ContactQuery cq=new ContactQuery();
            cq.deleteContact(id);

            jTable1.setModel(new DefaultTableModel());
            populateJTable();
            setTableProperties();
            clearFields();
        }else{
            JOptionPane.showMessageDialog(null,"Choose some contact to delete");
        }
        
            
    }//GEN-LAST:event_jButton_DeleteContactActionPerformed

    private void jButton_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_NextActionPerformed
        int rowIndex = jTable1.getSelectedRow()-1;
        try{
            showData(rowIndex);
            jTable1.setRowSelectionInterval(rowIndex,rowIndex);
        }catch(ArrayIndexOutOfBoundsException ex){
            JOptionPane.showMessageDialog(null, "It's the first contact on your list!");
        }
        
        
    }//GEN-LAST:event_jButton_NextActionPerformed

    private void jButton_PreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_PreviousActionPerformed
        int rowIndex = jTable1.getSelectedRow()+1;
        try{
            showData(rowIndex);
            jTable1.setRowSelectionInterval(rowIndex,rowIndex);
        }catch(ArrayIndexOutOfBoundsException ex){
            JOptionPane.showMessageDialog(null, "It's the last contact on your list!");
        }
        
    }//GEN-LAST:event_jButton_PreviousActionPerformed

    private void jButton_FirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_FirstActionPerformed
        int rowIndex = 0;
        showData(rowIndex);
        jTable1.setRowSelectionInterval(rowIndex,rowIndex);
    }//GEN-LAST:event_jButton_FirstActionPerformed

    private void jButton_LastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LastActionPerformed
        int rowIndex = jTable1.getRowCount()-1;
        jTable1.setRowSelectionInterval(rowIndex,rowIndex);
        showData(rowIndex);
    }//GEN-LAST:event_jButton_LastActionPerformed

    private void jButton_DeleteContact1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DeleteContact1ActionPerformed
        LoginForm lf=new LoginForm();
        lf.setVisible(true);
        lf.pack();
        lf.setLocationRelativeTo(null);
        lf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();    
    }//GEN-LAST:event_jButton_DeleteContact1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContactBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContactBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContactBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContactBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContactBookForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_AddContact;
    private javax.swing.JButton jButton_Browse;
    private javax.swing.JButton jButton_DeleteContact;
    private javax.swing.JButton jButton_DeleteContact1;
    private javax.swing.JButton jButton_EditContact;
    private javax.swing.JButton jButton_First;
    private javax.swing.JButton jButton_Last;
    private javax.swing.JButton jButton_Next;
    private javax.swing.JButton jButton_Previous;
    private javax.swing.JComboBox<String> jComboBox_Group;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Pic;
    public javax.swing.JLabel jLabel_UserPic;
    public javax.swing.JLabel jLabel_Username;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea_Address;
    private javax.swing.JTextField jTextField_Email;
    private javax.swing.JTextField jTextField_FName;
    private javax.swing.JTextField jTextField_Id;
    private javax.swing.JTextField jTextField_LName;
    private javax.swing.JTextField jTextField_Phone;
    // End of variables declaration//GEN-END:variables
}
